# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f97f877fa598ac4c019339e1e23136f0ce62ff0bc1f73b7ce30dd0403e143152fe7c0ce1471f8284b7df9926a80b0ee9160ae90efa16dd3c722e95b0904622a1

test:
  secret_key_base: a69d07123b2b58aab93dea2b610e1a9286bdcd63a114be4eb16887c83e539fc8e4e2af46fa9dafd57cb35a7db1e34b8227f0f6c119742d29fb6fc6e2c52722e5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
